apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: subscriber
  namespace: firedex
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: subscriber
        version: v1
        type: mqtt
    spec:
      initContainers:
      - name: init-subscriber
        image: busybox:1.28
        command: ['sh', '-c', 'echo "waiting for setup"; sleep 50; echo "starting subscribers"']
      containers:
      - name: firedex
        image: hemanthmalla/firedex:latest
        # TODO : Only for local testing
        imagePullPolicy: Never
        env:
        - name: ROLE
          value: subscriber
        volumeMounts:
        - mountPath: /var/log/subscriber
          name: logs
        - mountPath: /opt/firedex/subscriber_configurations
          name: configurations  
        ports:
        - containerPort: 10001 
        - containerPort: 10002
      restartPolicy: Always
      volumes:
      - name: logs
        hostPath:
          # directory location on host
          path: /home/docker/data/subscriber
          type: Directory
      - name: configurations
        hostPath:
          # directory location on host
          path: /home/docker/data/experimental_configuration/subscribers
          type: Directory
              
---
apiVersion: v1
kind: Service
metadata:
  name: subscriber
  namespace: firedex
  labels:
    app: subscriber
spec:
  ports:
  - port: 9999
    name: tcp
  selector:
    app: subscriber